#!/usr/bin/env python3
"""Generate a sample source document from a catalog JSON mapping file.

Reads a mapping in the shared catalog format (``config/mappings/<type>.mapping.json``): a ``root``
document block plus named subdocument blocks. Each field declares a ``type`` (``string``, ``freetext``,
``datetime``, ``number``, ``boolean``, ``subdocument``); ``subdocument`` fields reference another block via
``subdocumentType``. Values are generated by type, and subdocument fields expand into arrays of child objects.

The document is keyed by the mapping's logical field names. With ``--exclude-missing`` (plus an optional
``--datasource``), fields whose sourcing for that datasource is declared ``"required": false`` are omitted.
"""
from __future__ import annotations

import argparse
import json
import random
import string
import sys
from collections import OrderedDict
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

RESERVED_DOCUMENT_KEYS = {"block_mask"}
DEFAULT_DATASOURCE_FALLBACKS = ("default", "*")


@dataclass
class Options:
    multi: bool
    exclude_missing: bool
    datasource: str


def random_string(length: int = 10) -> str:
    alphabet = string.ascii_letters
    return "".join(random.choice(alphabet) for _ in range(length))


def random_number() -> int:
    return random.randint(1, 10_000)


def random_boolean() -> bool:
    return bool(random.getrandbits(1))


def random_datetime() -> str:
    delta = timedelta(days=random.randint(0, 3650), seconds=random.randint(0, 86_399))
    moment = datetime(2015, 1, 1, tzinfo=timezone.utc) + delta
    return moment.strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_value(value_type: str) -> Any:
    lowered = (value_type or "string").lower()
    if lowered == "number":
        return random_number()
    if lowered == "boolean":
        return random_boolean()
    if lowered == "datetime":
        return random_datetime()
    # string, freetext, predicate and anything else
    return random_string()


def sourcing_for(field: Dict[str, Any], key: str, datasource: str) -> Optional[Any]:
    """Resolve a per-datasource sourcing entry (``sourcing`` or ``primaryKey``) with default/* fallbacks."""
    block = field.get(key)
    if not isinstance(block, dict):
        return None
    for candidate in (datasource, *DEFAULT_DATASOURCE_FALLBACKS):
        if candidate in block:
            return block[candidate]
    return None


def is_optional(field: Dict[str, Any], datasource: str) -> bool:
    key = "primaryKey" if (field.get("type") or "").lower() == "subdocument" else "sourcing"
    expression = sourcing_for(field, key, datasource)
    return isinstance(expression, dict) and expression.get("required") is False


def generate_block(block: Dict[str, Any], mapping: Dict[str, Any], options: Options) -> "OrderedDict[str, Any]":
    result: "OrderedDict[str, Any]" = OrderedDict()
    for name, field in block.items():
        if name in RESERVED_DOCUMENT_KEYS or not isinstance(field, dict):
            continue
        if options.exclude_missing and is_optional(field, options.datasource):
            continue
        result[name] = generate_field(field, mapping, options)
    return result


def generate_field(field: Dict[str, Any], mapping: Dict[str, Any], options: Options) -> Any:
    field_type = (field.get("type") or "string").lower()
    if field_type == "subdocument":
        subdocument_type = field.get("subdocumentType")
        sub_block = mapping.get(subdocument_type)
        if not isinstance(sub_block, dict):
            raise ValueError(f"Subdocument type '{subdocument_type}' is not defined in the mapping")
        count = random.randint(2, 4) if options.multi else 1
        return [generate_block(sub_block, mapping, options) for _ in range(count)]
    return generate_value(field_type)


def resolve_mapping_path(argument: str) -> Path:
    candidate = Path(argument)
    if candidate.is_file():
        return candidate
    mapping_dir = Path("config/mappings")
    for suffix in (".mapping.json", ".json"):
        alt = mapping_dir / f"{argument}{suffix}"
        if alt.is_file():
            return alt
    raise FileNotFoundError(f"Unable to locate mapping file for '{argument}'")


def build_output_path(output_dir: Path, mapping_path: Path) -> Path:
    stem = mapping_path.name
    for suffix in (".mapping.json", ".json"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return output_dir / f"{stem}_{timestamp}.json"


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mapping", help="Name or path of the catalog JSON mapping file")
    parser.add_argument(
        "--output-dir",
        default="documents",
        help="Directory where the generated JSON document will be written",
    )
    parser.add_argument(
        "--multi",
        action="store_true",
        help="Generate subdocument arrays with multiple entries",
    )
    parser.add_argument(
        "--exclude-missing",
        action="store_true",
        help="Exclude fields whose sourcing for --datasource is declared 'required: false'",
    )
    parser.add_argument(
        "--datasource",
        default="default-datasource",
        help="Datasource whose sourcing 'required' flags drive --exclude-missing",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional random seed for reproducible output",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = parse_args(argv)
    if args.seed is not None:
        random.seed(args.seed)

    mapping_path = resolve_mapping_path(args.mapping)
    with mapping_path.open("r", encoding="utf-8") as fp:
        mapping = json.load(fp)

    root = mapping.get("root")
    if not isinstance(root, dict):
        raise ValueError("Mapping must contain a 'root' document block")

    options = Options(multi=args.multi, exclude_missing=args.exclude_missing, datasource=args.datasource)
    generated = generate_block(root, mapping, options)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = build_output_path(output_dir, mapping_path)

    with output_path.open("w", encoding="utf-8") as fp:
        json.dump(generated, fp, indent=2)
        fp.write("\n")

    print(f"Generated document written to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
