quarkus:
  http:
    port: 8080
  swagger-ui:
    always-include: true

indexer:
  catalog:
    source: file
    file:
      mappings:
        book:
          physical: config/mappings/book.mapping.json
          virtual: config/mappings/book.virtual.json
        article:
          physical: config/mappings/article.mapping.json
        ds:
          physical: config/mappings/dataset.mapping.json

monk3:
  search:
    material-type-field: material_type
    backends: {}
    solr:
      parent-block-mask: "*:* -_nest_path_:*"
